## Python Module and Package

In [ ]:

from packageA.resource import pr
# import functions from a module

# import functions from a package




hi


## Control Flow

In [ ]:
# if 
# else

# while

# for


## Vector/matrix operations

In [11]:
import numpy as np

In [14]:
# define a vector
x = np.array([1, 2, 3, 4])
print(x)
print(x.shape)

# transpose x
print(x.T)

x == x.T

[1 2 3 4]
(4,)
[1 2 3 4]


array([ True,  True,  True,  True])

In [18]:
x / 2

array([0.5, 1. , 1.5, 2. ])

In [21]:
# how about the following code?
x = np.array([1, 2, 3, 4])
print(x.dot(x))

30


In [ ]:
# matrix multiplication
A = np.random.randn(4,3)
C = np.random.randn(3,2)
print(np.shape(A))
print(np.shape(C))

print(A.dot(C))
print('=======')
print(np.dot(A,C))


(4, 3)
(3, 2)
[[ 0.11960342  1.25453601]
 [-0.84462071  0.47862569]
 [ 1.50776488 -1.06569701]
 [-1.90085327  2.75265387]]
[[ 0.11960342  1.25453601]
 [-0.84462071  0.47862569]
 [ 1.50776488 -1.06569701]
 [-1.90085327  2.75265387]]


In [ ]:
# conformability


array([[1., 0.],
       [0., 1.]])

## Pass Activity

Define a string with a value equal to “Python is fun!”. Print every third character of this string.

Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.

Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.


In [ ]:

# Define a string with a value equal to “Python is fun!”. Print every third character of this string.
string = "Python is fun!"
print(string[2::3])

# Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.
StudentName = np.random.randn(5)
ID  = np.random.randn(5)
EmailAddress = np.random.randn(5)

print(StudentName)
print(ID)
print(EmailAddress)


# Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.
d = {"StudentName": None, "ID":None, "EmailAddress": None }
for key in d:
  if key == "StudentName":
    d[key] = StudentName
  elif key == "ID":
    d[key] = ID
  else: 
    d[key] = EmailAddress

print(d)

In [ ]:
import pandas as pd

pd.read_csv("data/data.csv")