In [3]:
import numpy as np
from packageA.resource import pr

## Python Module and Package

In [5]:
# import functions from a module

# import functions from a package


hi


## Vector/matrix operations

In [13]:
# define a vector
x = np.array([1, 2, 3, 4])
print(x)
print(x.shape)

# transpose x
print(x.T)

# dot product
print(x.dot(x.T))

[1 2 3 4]
(4,)
[1 2 3 4]
30


In [16]:
# how about the following code?
x.shape = [4, 1] # force it to be a column vector
print(x)
print(x.shape)
print(x.T)
print(x.dot(x.T))

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [3]:
# matrix multiplication
A = np.random.randn(4,3)
C = np.random.randn(3,2)
print(np.shape(A))
print(np.shape(C))

print(A.dot(C))
print('=======')
print(np.dot(A,C))


(4, 3)
(3, 2)
[[ 0.11960342  1.25453601]
 [-0.84462071  0.47862569]
 [ 1.50776488 -1.06569701]
 [-1.90085327  2.75265387]]
[[ 0.11960342  1.25453601]
 [-0.84462071  0.47862569]
 [ 1.50776488 -1.06569701]
 [-1.90085327  2.75265387]]


In [4]:
# conformability


array([[1., 0.],
       [0., 1.]])

## Pass Activity

Define a string with a value equal to “Python is fun!”. Print every third character of this string.

Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.

Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.
